/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package etapa2projetosin142;

import java.awt.Color;
/**
 *
 * @author edunu
 */
public class frmVisualizar extends javax.swing.JFrame {
  
        int i;
        CountSemap m = new CountSemap();
        
    /**
     * Creates new form frmVisualizar
     */
    public frmVisualizar() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        LabelLike = new javax.swing.JLabel();
        LabelLike1 = new javax.swing.JLabel();
        LabelLike2 = new javax.swing.JLabel();
        LViews = new javax.swing.JLabel();
        LLikes = new javax.swing.JLabel();
        LDislikes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 102));
        jButton1.setText("Executar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        LabelLike.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        LabelLike.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelLike.setText("Final de Likes:");
        LabelLike.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelLike1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        LabelLike1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelLike1.setText("Final de Dislikes:");
        LabelLike1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LabelLike2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        LabelLike2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelLike2.setText("Final de Views:");
        LabelLike2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        LViews.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LViews.setEnabled(false);

        LLikes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LLikes.setEnabled(false);

        LDislikes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LDislikes.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelLike2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LViews))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelLike)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelLike1)
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LDislikes)
                            .addComponent(LLikes))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLike2)
                    .addComponent(LViews))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelLike)
                            .addComponent(LLikes)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLike1)
                    .addComponent(LDislikes))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int aux;
        m.semafaro();
        
        try{
            m.sleep(400);
        }catch(Exception e){
            System.out.println("Deu erro!");
        }
        
        aux = m.getViews();

        LViews.enable();
        LViews.setForeground(Color.blue);
        LViews.setText(String.valueOf(aux));

        aux = m.getLike();
        LLikes.enable();
        LLikes.setForeground(Color.blue);
        LLikes.setText(String.valueOf(aux));

        aux = m.getDislike();
        LDislikes.enable();
        LDislikes.setForeground(Color.blue);
        LDislikes.setText(String.valueOf(aux));
  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVisualizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVisualizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDislikes;
    private javax.swing.JLabel LLikes;
    private javax.swing.JLabel LViews;
    private javax.swing.JLabel LabelLike;
    private javax.swing.JLabel LabelLike1;
    private javax.swing.JLabel LabelLike2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
